### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by j-rockwell** [ares-network/ares-paper#1]
**Spigot Server Patches**
- [ ] https://github.com/IPVP-MC/Paper-1.7/blob/master/Spigot-Server-Patches/0110-Don-t-randomize-damage-reduction-values-from-protect.patch
- [ ] https://github.com/IPVP-MC/Paper-1.7/blob/master/Spigot-Server-Patches/0112-Only-apply-1-damage-point-to-armor-when-an-entity-ta.patch
- [ ] https://github.com/IPVP-MC/Paper-1.7/blob/master/Spigot-Server-Patches/0096-Pull-knockback-fixes-from-SportBukkit.patch
- [ ] https://github.com/IPVP-MC/Paper-1.7/blob/master/Spigot-Server-Patches/0077-Send-absolute-position-the-first-time-an-entity-is-s.patch
- [ ] https://github.com/IPVP-MC/Paper-1.7/blob/master/Spigot-Server-Patches/0107-Add-configuration-option-to-allow-enderpearls-go-thr.patch
